name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Backend tests
      - name: Test backend
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest
          pytest backend/tests/

      # 3️⃣ Frontend tests
      - name: Test frontend
        run: |
          cd frontend
          npm install
          npm test -- --watchAll=false

      # 4️⃣ Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Build & push single Docker image
      - name: Build & push todo-app
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: usersid/todo-app-cicd:latest
